### ISSUE TITLE
Investigate OdinDeclaredIdentifierImpl PluginException breaking code completion on latest Odin HEAD

### ISSUE THREAD

**Issue by Dima-369** [obiwan87/odin-intellij#65]
When you type `if ` and then you want code completion, it does not show anything:

![CleanShot 2024-08-17 at 13 41 07@2x](https://github.com/user-attachments/assets/ae837d16-29de-445d-81d6-226662e68d13)

Here it works without `if`:

![CleanShot 2024-08-17 at 13 40 51@2x](https://github.com/user-attachments/assets/eeb46d7d-a345-4ba0-9301-0448f70f2532)

**Comment by Dima-369** [comment]
And say, I have those `import`s.

```odin
import "core:fmt"
import "core:os"
import "core:strings"
import "core:sys/posix"
import "core:time"
```

It would be great if `fmt`, `os`, `strings`, etc. would be shown for the code completion. Same with variables, I just find it a bit strange since I thought that it had worked before?

**Comment by Dima-369** [comment]
There must have been a crash somewhere, I just restarted IntelliJ and it works again.

**Comment by Dima-369** [comment]
Reproducible. I see this stack trace, maybe worth investigating, I used the latest HEAD of Odin.

Once that error is shown, code completion breaks in the ways shown above:

```
com.intellij.diagnostic.PluginException: Element: class com.lasagnerd.odin.lang.psi.impl.OdinDeclaredIdentifierImpl #Odin  because: different providers: com.intellij.psi.SingleRootFileViewProvider{vFile=file:///opt/homebrew/Cellar/odin/HEAD-478f529/libexec/base/runtime/core_builtin.odin, vFileId=763636, content=VirtualFileContent{size=33270}, eventSystemEnabled=true}(163c6b26); com.intellij.psi.SingleRootFileViewProvider{vFile=file:///opt/homebrew/Cellar/odin/HEAD-478f529/libexec/base/runtime/core_builtin.odin, vFileId=763636, content=VirtualFileContent{size=33270}, eventSystemEnabled=true}(4a1f1a7d)
invalidated at: see attachment [Plugin: com.lasagnerd.odin]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:100)
	at com.intellij.psi.util.PsiUtilCore.ensureValid(PsiUtilCore.java:510)
	at com.intellij.codeInsight.lookup.LookupElementBuilder.create(LookupElementBuilder.java:92)
	at com.lasagnerd.odin.codeInsight.completion.OdinCompletionContributor.addLookUpElements(OdinCompletionContributor.java:234)
	at com.lasagnerd.odin.codeInsight.completion.OdinCompletionContributor.addLookUpElements(OdinCompletionContributor.java:178)
	at com.lasagnerd.odin.codeInsight.completion.OdinCompletionContributor$2.addCompletions(OdinCompletionContributor.java:162)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:23)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:156)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributor(CompletionService.java:81)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.getVariantsFromContributor(CompletionServiceImpl.kt:220)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:73)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:150)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:142)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:138)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$1.addCompletions(LiveTemplateCompletionContributor.java:87)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:23)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:156)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributor(CompletionService.java:81)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.getVariantsFromContributor(CompletionServiceImpl.kt:220)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:73)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:56)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:130)
	at com.intellij.codeInsight.completion.BaseCompletionService.performCompletion(BaseCompletionService.java:48)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.performCompletion(CompletionServiceImpl.kt:235)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.lambda$calculateItems$12(CompletionProgressIndicator.java:974)
	at com.intellij.util.indexing.FileBasedIndex.lambda$ignoreDumbMode$0(FileBasedIndex.java:225)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.util.indexing.FileBasedIndexEx.ignoreDumbMode(FileBasedIndexEx.java:645)
	at com.intellij.util.indexing.FileBasedIndex.ignoreDumbMode(FileBasedIndex.java:224)
	at com.intellij.util.indexing.DumbModeAccessType.ignoreDumbMode(DumbModeAccessType.java:41)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:970)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:958)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$startContributorThread$7(CodeCompletionHandlerBase.java:383)
	at io.opentelemetry.context.Context.lambda$wrap$1(Context.java:212)
	at com.intellij.codeInsight.completion.CompletionThreadingKt.tryReadOrCancel$lambda$0(CompletionThreading.kt:76)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:291)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
	at com.intellij.codeInsight.completion.CompletionThreadingKt.tryReadOrCancel(CompletionThreading.kt:74)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$startContributorThread$8(CodeCompletionHandlerBase.java:375)
	at io.opentelemetry.context.Context.lambda$wrap$1(Context.java:212)
	at com.intellij.codeInsight.completion.AsyncCompletion.startThread$lambda$1$lambda$0(CompletionThreading.kt:98)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:217)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202)
	at com.intellij.codeInsight.completion.AsyncCompletion.startThread$lambda$1(CompletionThreading.kt:93)
	at com.intellij.codeInsight.completion.AsyncCompletion$startThread$future$1.invokeSuspend(CompletionThreading.kt:104)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.SoftLimitedDispatcher$Worker.run(SoftLimitedDispatcher.kt:125)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
Caused by: com.intellij.psi.PsiInvalidElementAccessException: Element: class com.lasagnerd.odin.lang.psi.impl.OdinDeclaredIdentifierImpl #Odin  because: different providers: com.intellij.psi.SingleRootFileViewProvider{vFile=file:///opt/homebrew/Cellar/odin/HEAD-478f529/libexec/base/runtime/core_builtin.odin, vFileId=763636, content=VirtualFileContent{size=33270}, eventSystemEnabled=true}(163c6b26); com.intellij.psi.SingleRootFileViewProvider{vFile=file:///opt/homebrew/Cellar/odin/HEAD-478f529/libexec/base/runtime/core_builtin.odin, vFileId=763636, content=VirtualFileContent{size=33270}, eventSystemEnabled=true}(4a1f1a7d)
invalidated at: see attachment
	... 57 more
```

**Comment by obiwan87** [comment]
Hmm, weird. It looks like a caching problem to me.  Can you please empty the caches and retry?

**Comment by Dima-369** [comment]
Yes, I switched to Odin HEAD. Seems fine for now with all caches reset, closing for now.
